CREATE PROC FI_SP_ConsBeneficiario
	@IDCLIENTE BIGINT = NULL,
	@ID BIGINT = NULL
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT ID, NOME, CPF, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @IDCLIENTE
	ELSE
		SELECT ID, NOME, CPF, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK) WHERE ID = @ID
END
