CREATE PROC FI_SP_ConsCliente
	@ID BIGINT
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT NOME, SOBRENOME, CPF, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, ID, DELETADO FROM CLIENTES WITH(NOLOCK) WHERE ISNULL(DELETADO, 0) = 0
	ELSE
		SELECT NOME, SOBRENOME, CPF, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, ID, DELETADO FROM CLIENTES WITH(NOLOCK) WHERE ID = @ID AND ISNULL(DELETADO, 0) = 0
END